### ISSUE TITLE
Add `theme.json` with sensible defaults to the Theme Scaffold

### ISSUE THREAD

**Issue by fabiankaegy** [10up/wp-scaffold#57]
This is ment to be a tracking ticket for the different action items that will be needed in order to add support for `theme.json` in the Theme Scaffold. 

The Dev Note on make.wordpress.org says that these are the sideeffects of just adding an empty theme.json file to a theme:

> There are some features that are enabled or disabled when a theme has support for a theme.json file:
> 
> - The template editor is enabled.
> - The default layout and margin styles for themes are not enqueued and the new layout options are enabled instead (see related dev note for layout).
> - The inner div for the group block (wp-block-group__inner-container) is removed.
> - The default font-family styles for the editor are not enqueued.
>
> [https://make.wordpress.org/core/2021/06/25/introducing-theme-json-in-wordpress-5-8/](https://make.wordpress.org/core/2021/06/25/introducing-theme-json-in-wordpress-5-8/)

## Tasks:
- [ ] Add Theme Colors
- [ ] Add Theme Spacing 
- [ ] Add Theme Fonts

## Questions:
- [ ] If we follow the [IE: This is the End](https://internal.10up.com/blog/2021/08/31/ie11-this-is-the-end/) and don't worry about IE11 we can also refactor the colors to use the ones that are enqueued from WordPress Automatically by using the `theme.json. A great article about that can be fund here: https://richtabor.com/standardizing-theme-json-colors/
- [ ] Do we want to enable the Block Templates (Template Part Editor) in the default scaffold
( can get removed by adding `remove_theme_support( 'block-templates' );` in the `after_theme_setup` hook)
- [ ] Do we want to remove the DropCap option by default?

**Comment by fabiankaegy** [comment]
#33 This PR has been closed because of this

**Comment by joesnellpdx** [comment]
@fabiankaegy 

- [x] Yes, we can assume we are supporting IE11. 
- [ ] Enable the Block Templates? I don't know. What are your thoughts?
- [x] Remove drop caps by default? Yes - this is a good easy pattern to add to the `theme.json` by default and it can be assumed it will be removed by most projects out of the box

**Comment by fabiankaegy** [comment]
## Additional things I would like to cover as part of this introduction:
- [ ] Standardize how we load custom fonts in the editor (through defining the font in the theme.json and loading it via `add_editor_style`)
- [ ] Standardize how we use font size systems so that we no longer have the issue of differing `rem` values in the editor

**Comment by fabiankaegy** [comment]
I had a very productive conversation with @willhowat about this and he shared some of his findings from recent projects with me. Based on that conversation I think that the best way forward it to start by having a barebones `theme.json` to start with so that projects have all the changed functionality from the beginning. 

Once the whole responsive and contextual quesion is a bit more clear we can move forward with adding more in here by default.
